# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

imports:
    - { resource: 'app.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/**/!(*Repository).php'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller/*'
        tags: ['controller.service_arguments']

    App\UI\Cli\Command\:
        resource: '../src/UI/Cli/Command'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    _instanceof:
        App\Application\Shared\Command\CommandHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Application\Shared\Query\QueryHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Application\Shared\Event\EventHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    App\Application\Shared\Helper\SecurityHelper:
        arguments:
            $secret: '%app.secret%'

    App\Infrastructure\EventSubscriber\AuditableEntitySubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
